version: "3"
services:
    vinny:
        build: .
        environment:
            - VINNY_REDIS_HOST=redis
            - NODE_ENV=${NODE_ENV}
        depends_on:
            - redis
        image: vinny
    redis:
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
volumes:
    redis-data:
