apiVersion: v1
kind: Service
metadata:
  name: vinny-redis
spec:
  selector:
    app: vinny
    role: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vinny-redis
spec:
  serviceName: vinny-redis
  replicas: 1
  selector:
    matchLabels:
      app: vinny
      role: redis
  template:
    metadata:
      labels:
        app: vinny
        role: redis
    spec:
      containers:
        - name: redis
          image: "redis:alpine"
          volumeMounts:
            - name: data
              mountPath: /data
          args: ["--appendonly", "yes", "--aof-use-rdb-preamble", "yes"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi
