apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinny-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vinny
      role: worker
  template:
    metadata:
      labels:
        app: vinny
        role: worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - vinny
                    - key: role
                      operator: In
                      values:
                        - worker
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: vinny
          image: gcr.io/priv-224919/vinny
          env:
            - name: NODE_ENV
              value: development
          livenessProbe:
            exec:
              command:
                ["sh", "-c", "[ $(cat /tmp/alive) -gt $(($(date +%s) - 3)) ]"]
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
