apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: vinny
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vinny
    template:
        metadata:
            labels:
                app: vinny
        spec:
            containers:
                - name: vinny
                  image: gcr.io/priv-224919/vinny
                  env:
                      - name: NODE_ENV
                        value: production
                  volumeMounts:
                      - name: data
                        mountPath: /data
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 50Mi
